### ISSUE TITLE
first move attack

### ISSUE THREAD

**Issue by BuyMyBeard** [BuyMyBeard/dazel#2]
if first move is attack, prevents Dazel from taking furter inputs

**Comment by dreamy32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [u](https://trello.com/c/9baLNIgt/2-u)

**Comment by dreamy32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Déplacement personnage](https://trello.com/c/Rgbpyxft/3-d%C3%A9placement-personnage)
